services:
  pulse:
    build: .
    ports:
      - "8005:8000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
    restart: always
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome  # Use for AMD/x86_64 processors
    shm_size: "4gb"  # Increase shared memory
    environment:
      - SE_START_XVFB=true  # Enable Xvfb for non-headless operation
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_TIMEOUT=300
      - SE_LOG_LEVEL=ALL
    ports:
      - "4444:4444"  # Expose Selenium on port 4444
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.5'
